name: CI

on: [ push ]
  branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      # define a matrix of different job configurations
      matrix:
        node-version: latest
    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout my repository under $GITHUB_WORKSPACE, so my job can access it
      - uses: actions/checkout@v2
      # task name
      - name: Run a one-line script
        # runs a single command using the runners shell
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy my project