name: github pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.83.1'
        extended: true

    - name: Build
      run: hugo --gc --minify --buildFuture --cleanDestinationDir

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.TEST_KEY }}
        publish_branch: gh-pages
        publish_dir: ./build
        allow_empty_commit: true