name: Github Actions Demo

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout Version 2
        uses: actions/checkout@v2

      - name: Setup Node Version 3
        uses: actions/setup-node@v3
        with: 
          node-version: 'latest'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os}}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build